@baseUrl = http://localhost:3000/api/v1

### 
GET {{baseUrl}}/users

### Create a user with a hashed password
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "authUser",
    "password": "secure_password"
}

### Create a user without a required field
POST {{baseUrl}}/register
Content-Type: application/json

{
    "password": "secure_password"
}

### Login a user successfully
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "authUser",
    "password": "secure_password"
}

### Login a user with an incorrect password
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "authUser",
    "password": "insecure_password"
}

### Login a user that does not exist
POST {{baseUrl}}/login
Content-Type: application/json

{
    "username": "unauthUser",
    "password": "insecure_password"
}