@baseUrl = http://localhost:3000/api/v3
@resource = reviews
@url = {{baseUrl}}/{{resource}}
@UserId = 6340983da164024708bbc257
@WebsiteId = 63388af82731382bd4930413
@ReviewId = 6340a08fb6bf2a4884c53d29 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlUGljdHVyZVNyYyI6ImltYWdlcy9kZWZhdWx0X3VzZXJfaWNvbi5wbmciLCJkZXNjcmlwdGlvbiI6IkkgbGlrZSB0cnV0bGVzIiwiZGlzYWJsZWRGb3IiOjAsIndyaXR0ZW5SZXZpZXdzIjpbXSwiX2lkIjoiNjM0MGM5MjY4YzhhMjExMjYwMThlYzQ5IiwidXNlcm5hbWUiOiJhbnNpc2hpaGkiLCJwYXNzd29yZCI6IiQyYiQxMCQxZ1YzMG91SUZiWHBXb2tSdThwNTFPRTl4blI4Q0xQV1NYYzdyUVVMeUJDdml1OVRQV3lTVyIsImNyZWF0ZWRBdCI6IjIwMjItMTAtMDhUMDA6NDk6NDIuMDA5WiIsInVwZGF0ZWRBdCI6IjIwMjItMTAtMDhUMDA6NDk6NDIuMDA5WiIsIl9fdiI6MCwiaWF0IjoxNjY1MTkwMjI0fQ.a3XEw-N8EK-xRx_gn_eEG7pDJNAWnyGRK4Y9NMeD3bk

#################################
############## GET ##############
#################################

### Get all reviews
GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### Get a review by its id
GET {{url}}/{{ReviewId}} HTTP/1.1
Authorization: Bearer {{token}}

### Get all user reviews
GET {{url}}/?username=ansishihi HTTP/1.1
Authorization: Bearer {{token}}

#################################
############# POST ##############
#################################

### Create a review for a user
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Possimus dolorum sequi velit ipsam veniam perspiciatis corrupti, delectus sit, magni consectetur sapiente, aliquam laborum nihil quae ut? Repudiandae cumque eveniet sed. Optio laudantium neque dolorem enim quaerat delectus fuga, nam amet at assumenda praesentium qui ipsa laborum beatae exercitationem excepturi et, vel possimus sapiente quo consequuntur soluta ullam. Ratione obcaecati neque impedit sit omnis, molestiae cupiditate? Error voluptatibus ipsam non provident unde! Eaque, harum consequuntur. Recusandae aliquam nesciunt perferendis tempora ipsa. Porro cupiditate, corrupti omnis praesentium vero aliquam fuga, maxime enim accusamus eveniet iusto quas. Dolores soluta voluptates ut. Quisquam, praesentium.",
    "rating": 4,
    "website": "Facebook"
}

### Create a review for a non-existent user
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "It's alright",
    "rating": 3,
    "website": "YouTube",
    "writtenBy": "nonexistentuser"
}

### Create a review for a non-existent website
POST {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "It's alright",
    "rating": 3,
    "website": "SkylarWhiteYo",
    "writtenBy": "updatedUsername"
}

#################################
############ DELETE #############
#################################

### Delete a review
DELETE {{url}}/63409c44f7b8dc5a388bd870 HTTP/1.1
Authorization: Bearer {{token}}

### Delete all reviews
DELETE {{url}} HTTP/1.1
Authorization: Bearer {{token}}