@baseUrl = http://localhost:3000/api/v3
@resource = users
@url = {{baseUrl}}/{{resource}}
@ObjectId = 6340983da164024708bbc257
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlUGljdHVyZVNyYyI6ImltYWdlcy9kZWZhdWx0X3VzZXJfaWNvbi5wbmciLCJkZXNjcmlwdGlvbiI6IkhlbGxvIE1vb24hIiwiZGlzYWJsZWRGb3IiOjAsIndyaXR0ZW5SZXZpZXdzIjpbXSwiX2lkIjoiNjM0MDk4M2RhMTY0MDI0NzA4YmJjMjU3IiwidXNlcm5hbWUiOiJ1c2VyIiwicGFzc3dvcmQiOiIkMmIkMTAkem0uakQudHZVcHZOQjdNT3V0bVVqdUxOamtOb2h2a3R4d28ydlZESTZUMzQ1Q09qeWFibDIiLCJjcmVhdGVkQXQiOiIyMDIyLTEwLTA3VDIxOjIxOjAxLjkzMloiLCJ1cGRhdGVkQXQiOiIyMDIyLTEwLTA3VDIxOjIxOjAxLjkzMloiLCJfX3YiOjAsImlhdCI6MTY2NTE3NzY2M30.NtupY86vQeSp6uSWaoEQ6cVNc5ewBMl-WcIhG3EU_lI

#################################
############## GET ##############
#################################

### Get a list of all users
GET {{url}} HTTP/1.1
Authorization: Bearer {{token}}

### Get a user by their id
GET {{url}}/{{ObjectId}} HTTP/1.1
Authorization: Bearer {{token}}

### Get a user by an invalid ObjectId
GET {{url}}/{{ObjectId}}2 HTTP/1.1
Authorization: Bearer {{token}}

### Get a user by a valid non-existent ObjectId
GET {{url}}/634095b9474f2d6100e4cc6e HTTP/1.1
Authorization: Bearer {{token}}

#################################
############## PUT ##############
#################################

### Replace a user with a valid body
PUT {{url}}/{{ObjectId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "replacedUsername",
    "password": "replacedPassword"
}

### Replace a user with an invalid body
PUT {{url}}/{{ObjectId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "username": "replacedUsername"
}

#################################
############# PATCH #############
#################################

### Update a user
PATCH {{url}}/{{ObjectId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "profilePictureSrc": "barox"
}

#################################
############ DELETE #############
#################################

### Delete a user
DELETE {{url}}/{{ObjectId}} HTTP/1.1
Authorization: Bearer {{token}}

### Delete all users
DELETE {{url}} HTTP/1.1
Authorization: Bearer {{token}}