@baseUrl = http://localhost:3000/api/v1
@resource = websites

### POST a specific website
POST {{baseUrl}}/{{resource}} HTTP/1.1
Content-Type: application/json

{
    "name": "Google",
    "logo_src": "images/wow.png",
    "description": "testing, testing",
    "url": "www.google.com",
    "launch_date": "2015-01-01"
}

### GET all websites
GET {{baseUrl}}/{{resource}} HTTP/1.1

### GET specific website
GET {{baseUrl}}/{{resource}}/6318b32e6b2e394bcc0202ba HTTP/1.1

### PUT specific website
PUT {{baseUrl}}/{{resource}}/6318b32e6b2e394bcc0202ba HTTP/1.1
Content-Type: application/json

{
    "logo_src": "images/updated.png",
    "description": "testy testy",
    "url": "www.yahoo.com",
    "launch_date": "2022-01-01"
}

### PATCH specific website
PUT {{baseUrl}}/{{resource}}/6318b32e6b2e394bcc0202ba HTTP/1.1
Content-Type: application/json

{
    "logo_src": "images/updated.png",
    "description": "testy testy",
    "url": "www.yahoo.com",
    "launch_date": "2022-01-01"
}

### DELETE specific website
DELETE {{baseUrl}}/{{resource}}/6318b32e6b2e394bcc0202ba HTTP/1.1

### DELETE all websites
DELETE {{baseUrl}}/{{resource}} HTTP/1.1

### GET website creator
GET {{baseUrl}}/{{resource}}/6318b32e6b2e394bcc0202ba/createdBy HTTP/1.1